name: build

on:
#  push:
#    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
    paths:
    - 'benches/**'
    - 'crates/**'
    - 'examples/**'
    - 'src/**'
    - 'tests/**'
    - Cargo.toml
    - .github/workflows/build.yml

jobs:
  test:

    runs-on: ubuntu-latest
    container: 
      image: rust:1.65.0-bullseye

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Rust toolchains
      run: |
        rustc --version &&
        rustup --version &&
        cargo --version
      shell: bash
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
    - name: Install rustfmt and clippy
      run: rustup component add rustfmt clippy
    - name: Check format
      run: cargo fmt --check
    - name: Clippy lint
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --workspace
      shell: bash
